plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

javafx {
    version = '21.0.2'
    modules = ['javafx.controls', 'javafx.fxml']
}

application {
    mainClass = 'com.seuapp.desktop.App'
}

dependencies {
    implementation project(':core')
}

tasks.named('run') {
    workingDir = rootProject.projectDir
}
