plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
    id 'org.beryx.runtime' version '1.13.1'
}

javafx {
    version = '21.0.2'
    modules = ['javafx.controls', 'javafx.fxml']
}

application {
    mainClass = 'com.seuapp.desktop.Launcher'
}

dependencies {
    implementation project(':core')
}

tasks.named('run') {
    workingDir = rootProject.projectDir
}

def osName = System.getProperty('os.name').toLowerCase()

def isWindows = osName.contains('win')
def isLinux = osName.contains('linux')
def isMac = osName.contains('mac')

runtime {
    additive = true

    modules = [
        'jdk.unsupported'
    ]

    options = [
        '--strip-debug',
        '--compress', '2',
        '--no-header-files',
        '--no-man-pages'
    ]

    launcher {
        noConsole = true
    }

    jpackage {
        imageName = 'YoutubeConverter'
        appVersion = '0.1.0'
        skipInstaller = false

        imageOptions = isWindows
                ? ['--win-console']
                : []

        installerType =
                isWindows ? 'msi' :
                isLinux ? 'deb' :
                isMac ? 'dmg' :
                null

        installerOptions = isWindows
                ? [
                    '--win-menu',
                    '--win-shortcut'
                ]
                : []
    }
}
