plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
    id 'org.beryx.runtime' version '1.13.1'
}

javafx {
    version = '21.0.2'
    modules = ['javafx.controls', 'javafx.fxml']
}

application {
    mainClass = 'com.seuapp.desktop.App'
}

dependencies {
    implementation project(':core')
}

tasks.named('run') {
    workingDir = rootProject.projectDir
}


runtime {
    options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']
    modules = ['java.base', 'java.desktop', 'java.naming', 'java.logging']

    jpackage {
        imageName = 'YoutubeConverter'
        installerName = 'YoutubeConverter'

    
        imageOptions = ['--app-content', file("${rootProject.projectDir}/tools").absolutePath]

        
    }
}